# Generated by Django 3.0.1 on 2020-01-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PPG',
            fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WEIGHT', models.FloatField()),
                ('Gender', models.BooleanField()),
                ('AGE', models.FloatField()),
                ('HEIGHT', models.FloatField()),
                ('SKIN', models.FloatField()),
                ('SPORT', models.FloatField()),
                ('Activity', models.FloatField()),
                ('label', models.FloatField()),
                ('ECG', models.FloatField()),
                ('EMG', models.FloatField()),
				('EDA', models.FloatField()),
                ('Temp', models.FloatField()),
                ('Resp', models.FloatField()),
                ('ACC1', models.FloatField()),
                ('ACC2', models.FloatField()),
				('ACC3', models.FloatField()),
                ('wACC1', models.FloatField()),
                ('wACC2', models.FloatField()),
				('wACC3', models.FloatField()),
                ('wBVP', models.FloatField()),
                ('wEDA', models.FloatField()),
                ('wTEMP', models.FloatField()),
				('created', models.DateTimeField(auto_now_add=True)),
            ],
 
        ),
    ]
